language: cpp
compiler: gcc

services:
  - docker

install:
  - sudo apt-get install -qq --force-yes mesa-utils libgl1-mesa-swx11 libgl1-mesa-swx11-dev xvfb  

#before_script:
#  - mvn clean

jobs:
  include:
    - stage: configure
#      install: skip
#      jdk: oraclejdk11
      script:
        - mkdir build
        - cd build
        - cmake ..
    - stage: build
      script: make

stages:
  - configure
  - build