language: cpp
compiler: gcc

services:
  - docker

install:
  - sudo apt-get install cmake libx11-dev xorg-dev libglu1-mesa-dev freeglut3-dev libglew1.5 libglew1.5-dev libglu1-mesa libglu1-mesa-dev libgl1-mesa-glx libgl1-mesa-dev

#before_script:
#  - mvn clean

jobs:
  include:
    - stage: build
      script:
        - mkdir build
        - cd build
        - cmake ..
        - make

stages:
  - configure
  - build